Output etc/demo.gif

Set Theme "Dracula"
Set FontSize 13
Set Width 1200
Set Height 650
Set Padding 20
Set PlaybackSpeed 1

Sleep 500ms

Type "sp devices"
Enter
Sleep 2s

Type "sp activate mjc"
Enter
Sleep 1s

Type `sp search tracks "bon iver"`
Enter
Sleep 3s
Type "q"
Sleep 500ms

Type `sp search albums "hozier"`
Enter
Sleep 3s
Type "q"
Sleep 500ms

Type "sp shelf"
Enter
Sleep 1s

Type "sp play abbeyroad --shuffle"
Enter
Sleep 1s

Type "sp pause"
Enter
Sleep 1s

Type "sp play"
Enter
Sleep 1s

Type "sp volume up"
Enter
Sleep 1s

Type "sp status"
Enter
Sleep 3s